[package]
name = "degreeworks_scraper"
version = "0.1.0"
authors = ["Benjamin Sherman <benjamin@bensherman.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.13.0"
anyhow = "1.0.32"
