name: Deploy to github pages
on:
  repository_dispatch:
    types: multi-sem-deploy
  push:
    branches:
      - multi-semester
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: "quacs/site"
          branch: "${GITHUB_REF##*/}"
          path: "gh-pages-site"

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run deploy script
        run: |
          git config user.name "QuACS" && git config user.email "github@quacs.org"
          yarn gh-pages-deploy
