name: Scrape new data
on:
  repository_dispatch:
    types: scrape
  # TODO Ideally this will only run when changes to the scraper folder are made
  # push:
  #   branches:
  #     - master

jobs:
  datadog-metrics:
    name: Send Datadog metrics
    runs-on: ubuntu-latest
    # needs:
    #   - commit-data
    steps:
      - name: Datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}

      - name: Checkout data repository
        uses: actions/checkout@v2
        with:
          path: "scrapers/data"
          repository: "quacs/quacs-data"
          ref: "master"
          clean: true
          token: ${{ secrets.GITHUBTOKEN }}

      - name: Generate and send metrics
        working-directory: ./scrapers
        run: python3 datadog/send_metrics.py